version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.12.0
      - image: mdillon/postgis
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bonder-test
          POSTGRES_USER: postgres
          PGUSER: postgres
          TZ: UTC
    resource_class: large
    environment:
      NODE_ENV: test
      TZ: UTC
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: make install
      - run:
          name: Lint Code
          command: make lint
      - run:
          name: Run tests
          command: make test
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy-dev:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run:
          name: Deploy to dev
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master
  deploy-staging:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run:
          name: Deploy to staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP_NAME.git staging:master
workflows:
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
